import { FixProposal, IssueContext } from './types.js';

export interface GitHubConfig {
  owner: string;
  repo: string;
  token?: string; // Optional - will use gh CLI if not provided
}

export class GitHubService {
  private owner: string;
  private repo: string;
  private token?: string;

  constructor(config: GitHubConfig) {
    this.owner = config.owner;
    this.repo = config.repo;
    this.token = config.token;
  }

  /**
   * Create a draft pull request using gh CLI
   */
  async createDraftPR(
    branchName: string,
    baseBranch: string,
    title: string,
    body: string
  ): Promise<string> {
    const { execSync } = require('child_process');

    try {
      // Use gh CLI to create draft PR
      const command = [
        'gh pr create',
        `--title "${this.escapeQuotes(title)}"`,
        `--body-file -`, // Read body from stdin
        `--base ${baseBranch}`,
        `--head ${branchName}`,
        '--draft',
      ].join(' ');

      const prUrl = execSync(command, {
        input: body,
        encoding: 'utf-8',
      }).trim();

      return prUrl;
    } catch (error: any) {
      throw new Error(`Failed to create PR: ${error.message}`);
    }
  }

  /**
   * Generate PR title from issue
   */
  generatePRTitle(context: IssueContext): string {
    const shortId = context.issue.shortId;
    const title = context.issue.title;

    // Truncate title if too long
    const maxLength = 60;
    const truncatedTitle =
      title.length > maxLength ? title.substring(0, maxLength) + '...' : title;

    return `fix(${shortId}): ${truncatedTitle}`;
  }

  /**
   * Generate PR body from analysis and proposal
   */
  generatePRBody(context: IssueContext, proposal: FixProposal): string {
    let body = `## 🤖 Automated Fix Proposal\n\n`;
    body += `This PR was automatically generated to fix a Sentry issue.\n\n`;

    body += `### Issue Details\n\n`;
    body += `- **Sentry Issue**: [${context.issue.shortId}](${context.issue.permalink})\n`;
    body += `- **Error**: ${context.errorType}: ${context.errorMessage}\n`;
    body += `- **Occurrences**: ${context.issue.count}\n`;
    body += `- **First Seen**: ${context.issue.firstSeen}\n`;
    body += `- **Last Seen**: ${context.issue.lastSeen}\n\n`;

    body += `### Analysis\n\n`;
    body += `${proposal.analysis}\n\n`;

    body += `### Proposed Changes\n\n`;
    if (proposal.proposedChanges.length > 0) {
      for (const change of proposal.proposedChanges) {
        body += `#### \`${change.file}\`\n\n`;
        body += `${change.description}\n\n`;

        if (change.code) {
          body += `<details>\n<summary>View proposed code</summary>\n\n`;
          body += `\`\`\`\n${change.code}\n\`\`\`\n\n`;
          body += `</details>\n\n`;
        }
      }
    } else {
      body += `See commits for detailed changes.\n\n`;
    }

    body += `### Confidence Level\n\n`;
    const confidenceEmoji = {
      high: '🟢',
      medium: '🟡',
      low: '🔴',
    };
    body += `${confidenceEmoji[proposal.confidence]} **${proposal.confidence.toUpperCase()}**\n\n`;

    body += `### Testing Checklist\n\n`;
    body += `- [ ] Code compiles without errors\n`;
    body += `- [ ] Tests pass\n`;
    body += `- [ ] Manual testing performed\n`;
    body += `- [ ] Error reproduced and verified fixed\n`;
    body += `- [ ] No new errors introduced\n\n`;

    body += `### ⚠️ Important Notes\n\n`;
    body += `- This is an **automated fix proposal** - please review carefully\n`;
    body += `- Test thoroughly before merging\n`;
    body += `- The fix is based on stack traces and available code context\n`;
    body += `- Additional changes may be needed\n\n`;

    body += `---\n\n`;
    body += `🤖 Generated by [Sentry-Claude Autofix](https://github.com/monta-app/sentry-claude-autofix)\n`;
    body += `💬 Powered by [Claude AI](https://claude.ai)\n`;

    return body;
  }

  /**
   * Generate commit message
   */
  generateCommitMessage(context: IssueContext, proposal: FixProposal): string {
    const shortId = context.issue.shortId;
    const title = context.issue.title;

    let message = `fix(${shortId}): ${title}\n\n`;

    // Add summary
    message += `Automated fix for Sentry issue ${shortId}\n\n`;

    // Add changes summary
    if (proposal.proposedChanges.length > 0) {
      message += `Changes:\n`;
      for (const change of proposal.proposedChanges) {
        message += `- ${change.file}: ${change.description}\n`;
      }
      message += `\n`;
    }

    // Add issue details
    message += `Issue Details:\n`;
    message += `- Error: ${context.errorType}\n`;
    message += `- Occurrences: ${context.issue.count}\n`;
    message += `- Link: ${context.issue.permalink}\n\n`;

    // Add analysis (truncated)
    const analysisPreview =
      proposal.analysis.length > 200
        ? proposal.analysis.substring(0, 200) + '...'
        : proposal.analysis;
    message += `Analysis:\n${analysisPreview}\n\n`;

    message += `Confidence: ${proposal.confidence}\n\n`;

    message += `🤖 Generated by Sentry-Claude Autofix\n`;
    message += `Co-Authored-By: Claude <noreply@anthropic.com>`;

    return message;
  }

  /**
   * Escape quotes in strings for shell commands
   */
  private escapeQuotes(str: string): string {
    return str.replace(/"/g, '\\"');
  }
}
